[rocks]

[plugins]
"rocks.nvim" = "2.43.0"
"rocks-git.nvim" = "2.5.2"
"rocks-treesitter.nvim" = "1.3.0"
"rocks-config.nvim" = "3.1.0"
nvim-lspconfig = "1.2.0"
"rocks-lazy.nvim" = "1.2.1"

[plugins.coq_nvim]
git = "ms-jpq/coq_nvim"
rev = "976012b0c13763a47edbd55492ba53b03b498cdd"

[plugins."ranger.nvim"]
git = "kelly-lin/ranger.nvim"
rev = "fd2cc999f3ef88f7cdcbcad5f26000c52b16c489"
[plugins."ranger.nvim".config.options]
config = true
enable_cmds = true
replace_netrw = true

[plugins.vim-zscript]
git = "marrub--/vim-zscript"
rev = "8c9352effb0847f838dbe32dc946ab38937b3d26"
